TRUNCATE TABLE USERS;

INSERT INTO USERS (id, name) VALUES (USERS_SEQ.NEXTVAL, 'Niels');
INSERT INTO USERS (id, name) VALUES (USERS_SEQ.NEXTVAL, 'Piels');
INSERT INTO USERS (id, name) VALUES (USERS_SEQ.NEXTVAL, 'Stiels');